/* eslint-disable @next/next/no-sync-scripts */
import type { NextPage } from 'next';
import Head from 'next/head';
import Script from 'next/script';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script src="/static/app.js" strategy="beforeInteractive" />
      <main className="">
        <h1>Welcome to Next.js!</h1>
        <h2>Welcome to Next.js!</h2>
        <h3>Welcome to Next.js!</h3>
        <h4>Welcome to Next.js!</h4>
        <h5>Welcome to Next.js!</h5>
        <p>Morbi fringilla convallis sapien, id pulvinar odio volutpat. Cras mattis iudicium purus sit amet fermentum. At nos hinc posthac, sitientis piros Afros. Nec dubitamus multa iter quae et nos invenerat.
Pellentesque habitant morbi tristique senectus et netus. Morbi odio eros, volutpat ut pharetra vitae, lobortis sed nibh. Integer legentibus erat a ante historiarum dapibus. Quis aute iure reprehenderit in voluptate velit esse. Me non paenitet nullum festiviorem excogitasse ad hoc.
Gallia est omnis divisa in partes tres, quarum. Ab illo tempore, ab est sed immemorabili. Nihil hic munitissimus habendi senatus locus, nihil horum? Nihilne te nocturnum praesidium Palati, nihil urbis vigiliae.
Ut enim ad minim veniam, quis nostrud exercitation. Fabio vel iudice vincam, sunt in culpa qui officia. Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua.
Quam temere in vitiis, legem sancimus haerentia. Praeterea iter est quasdam res quas ex communi. Ambitioni dedisse scripsisse iudicaretur. Qui ipsorum lingua Celtae, nostra Galli appellantur. Contra legem facit qui id facit quod lex prohibet.
</p>

<p>Morbi fringilla convallis sapien, id pulvinar odio volutpat. Cras mattis iudicium purus sit amet fermentum. At nos hinc posthac, sitientis piros Afros. Nec dubitamus multa iter quae et nos invenerat.
Pellentesque habitant morbi tristique senectus et netus. Morbi odio eros, volutpat ut pharetra vitae, lobortis sed nibh. Integer legentibus erat a ante historiarum dapibus. Quis aute iure reprehenderit in voluptate velit esse. Me non paenitet nullum festiviorem excogitasse ad hoc.
Gallia est omnis divisa in partes tres, quarum. Ab illo tempore, ab est sed immemorabili. Nihil hic munitissimus habendi senatus locus, nihil horum? Nihilne te nocturnum praesidium Palati, nihil urbis vigiliae.
Ut enim ad minim veniam, quis nostrud exercitation. Fabio vel iudice vincam, sunt in culpa qui officia. Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua.
Quam temere in vitiis, legem sancimus haerentia. Praeterea iter est quasdam res quas ex communi. Ambitioni dedisse scripsisse iudicaretur. Qui ipsorum lingua Celtae, nostra Galli appellantur. Contra legem facit qui id facit quod lex prohibet.
</p>

<p>Morbi fringilla convallis sapien, id pulvinar odio volutpat. Cras mattis iudicium purus sit amet fermentum. At nos hinc posthac, sitientis piros Afros. Nec dubitamus multa iter quae et nos invenerat.
Pellentesque habitant morbi tristique senectus et netus. Morbi odio eros, volutpat ut pharetra vitae, lobortis sed nibh. Integer legentibus erat a ante historiarum dapibus. Quis aute iure reprehenderit in voluptate velit esse. Me non paenitet nullum festiviorem excogitasse ad hoc.
Gallia est omnis divisa in partes tres, quarum. Ab illo tempore, ab est sed immemorabili. Nihil hic munitissimus habendi senatus locus, nihil horum? Nihilne te nocturnum praesidium Palati, nihil urbis vigiliae.
Ut enim ad minim veniam, quis nostrud exercitation. Fabio vel iudice vincam, sunt in culpa qui officia. Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua.
Quam temere in vitiis, legem sancimus haerentia. Praeterea iter est quasdam res quas ex communi. Ambitioni dedisse scripsisse iudicaretur. Qui ipsorum lingua Celtae, nostra Galli appellantur. Contra legem facit qui id facit quod lex prohibet.
</p>

<p>Morbi fringilla convallis sapien, id pulvinar odio volutpat. Cras mattis iudicium purus sit amet fermentum. At nos hinc posthac, sitientis piros Afros. Nec dubitamus multa iter quae et nos invenerat.
Pellentesque habitant morbi tristique senectus et netus. Morbi odio eros, volutpat ut pharetra vitae, lobortis sed nibh. Integer legentibus erat a ante historiarum dapibus. Quis aute iure reprehenderit in voluptate velit esse. Me non paenitet nullum festiviorem excogitasse ad hoc.
Gallia est omnis divisa in partes tres, quarum. Ab illo tempore, ab est sed immemorabili. Nihil hic munitissimus habendi senatus locus, nihil horum? Nihilne te nocturnum praesidium Palati, nihil urbis vigiliae.
Ut enim ad minim veniam, quis nostrud exercitation. Fabio vel iudice vincam, sunt in culpa qui officia. Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua.
Quam temere in vitiis, legem sancimus haerentia. Praeterea iter est quasdam res quas ex communi. Ambitioni dedisse scripsisse iudicaretur. Qui ipsorum lingua Celtae, nostra Galli appellantur. Contra legem facit qui id facit quod lex prohibet.
</p>
      </main>
    </>
  );
};

export default Home;