import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-slate-900 min-h-screen">
        <h1 className="text-zinc-50">Welcome to Next.js!</h1>
        <h2 className="text-zinc-50">Welcome to Next.js!</h2>
        <h3 className="text-zinc-50">Welcome to Next.js!</h3>
        <h4 className="text-zinc-50">Welcome to Next.js!</h4>
        <h5 className="text-zinc-50">Welcome to Next.js!</h5>
        <p className="text-neutral-100">
          Quam diu etiam furor iste tuus nos eludet?
        </p>
      </main>
    </div>
  );
};

export default Home;
